<a href="https://colab.research.google.com/github/rubygitflow/Higher-Math/blob/main/University_of_Artificial_Intelligence_%D0%91%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0_%D0%97%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D0%B5_%E2%84%96_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Курс "Базовая математика"
#Занятие 1. Матрицы


## Действия над векторами (аналитическая  геометрия)

In [ ]:
# Даны две точки плоскости A(2,3) и B(-3,1). Найти координаты вектора AB
#AB  = (x2-x1,y2-y1)
print ("Vector's Coordinates: ({},{})".format((-3)-2,1-3))

Vector's Coordinates: (-5,-2)


In [ ]:
# Даны две точки плоскости A(1,3) и B(-3,-1). Найти модуль вектора AB
import numpy as np
#AB(x,y)  = sqrt(x**2 + y**2)
print ("Vector's Coordinates: ({},{})".format((-3)-1,(-1)-3))
print ("Vector's module: {}".format(np.sqrt( ((-3)-1)**2  + ((-1)-3)**2 )))

Vector's Coordinates: (-4,-4)
Vector's module: 5.656854249492381


In [ ]:
# Даны два вектора a(1,-3) и b(3,2). Найти: 2a, a+b, a-b
import numpy as np
#C * a(x,y) = b(C*x,C*y) 
#a(x1,y1) + b(x2,y2) = c(x1+x2,y1+y2) 
#a(x1,y1) - b(x2,y2) = c(x1-x2,y1-y2)  

class vector_2d:

  def __init__(self,coords):
    self.x = coords[0]
    self.y = coords[1]

  def scalar_miltiplier(self,scalar):
    return (self.x*scalar,self.y*scalar)

  def add_substract(self,v,type_='add'):
    if type_=='add':
      return (self.x+v.x,self.y+v.y)
    if type_=='subs':
      return (self.x-v.x,self.y-v.y)


a = vector_2d(coords=(1,-3))
b = vector_2d(coords=(3,2))


print (" a Coordinates: ({}, {})".format(a.x,a.y))
print (" b Coordinates: ({}, {})".format(b.x,b.y))
print (" 2*a: {}".format(a.scalar_miltiplier(2)))
print (" a+b: {}".format(a.add_substract(b)))
print (" a-b: {}".format(a.add_substract(b,type_='subs')))

 a Coordinates: (1, -3)
 b Coordinates: (3, 2)
 2*a: (2, -6)
 a+b: (4, -1)
 a-b: (-2, -5)


In [ ]:
# Найти скалярное произведение векторов a(1,4) и b(-3,2), если угол между a и b = pi/6
# a*b = |a|*|b| * cos(a,b)

class vector_2d:

  def __init__(self,coords):
    self.x = coords[0]
    self.y = coords[1]
  
  #add more functions
  def get_module(self):
    return np.sqrt(self.x**2 + self.y**2)
  
  @staticmethod
  def compute_cosine(rad):
    return np.cos(rad)

  def vector_product(self,v,rad):
    return (self.get_module() * v.get_module() * self.compute_cosine(rad))

  def scalar_miltiplier(self,scalar):
    return (self.x*scalar,self.y*scalar)

  def add_substract(self,v,type_='add'):
    if type_=='add':
      return (self.x+v.x,self.y+v.y)
    if type_=='subs':
      return (self.x-v.x,self.y-v.y)

a = vector_2d(coords=(1,4))
b = vector_2d(coords=(-3,2))

print (" a*b = {}".format(a.vector_product(b,np.pi/6)))  

 a*b = 12.874393189583733


In [ ]:
# нахождение угла:
# угол = arccos(a*b/|a|*|b|)
a = vector_2d(coords=(1,4))
b = vector_2d(coords=(-3,2))
a_b = 12.874393189583733
ang = a_b/(a.get_module() * b.get_module()) 
print (" Угол равен = {}".format(np.arccos(ang)))  



 Угол равен = 0.5235987755982987


In [ ]:
# Скалярное произведение векторов в координатах
# a(x1,x2)* b(y1,y2) = ab(x1*y1+x2*y2)
print (" Скалярное произведение ab в координатах = {}".format(a.x*b.x + a.y*b.y))  

 Скалярное произведение ab в координатах = 5


### Матрицы и действия над ними

In [ ]:
from copy import deepcopy

class Matrix():

  def __init__(self, matrix):
    self.matrix=matrix
    self.n = len(matrix)
    self.m = len(matrix[0])

  def scalar_miltiplier(self,scalar):
    
    for i in range(self.n):
      row = []
      for j in range(self.m):
        row.append(self.matrix[i][j]*scalar)
      self.matrix[i] = row

  def T(self):
    transpose = deepcopy(self.matrix)
    for i in range(self.n):
      for j in range(self.m):
        transpose[i][j] = self.matrix[j][i]
    return transpose



In [ ]:
m1 = Matrix([[1,2,3],
      [3,2,1],
      [0,0,1]
      ])

In [ ]:
m1.matrix

[[1, 2, 3], [3, 2, 1], [0, 0, 1]]

In [ ]:
m1.scalar_miltiplier(-1)
m1.matrix

[[-1, -2, -3], [-3, -2, -1], [0, 0, -1]]

In [ ]:
m1.T()


[[1, 3, 0], [2, 2, 0], [3, 1, 1]]

In [ ]:
def matrix_add(m1,m2):
  new_m = deepcopy(m1.matrix)
  print('m1.n =',m1.n)
  print('m1.m =',m1.m)
  for i in range(m1.n):
      for j in range(m1.m):
        new_m[i][j] = m1.matrix[i][j]+m2.matrix[i][j]
  return new_m


In [ ]:
matrix_add(m1,m1)

m1.n = 3
m1.m = 3


[[2, 4, 6], [6, 4, 2], [0, 0, 2]]

In [ ]:
def prod_matrix(m1, m2):
  n = m1.n
  m = m2.m
  
  
  out_matrix = []
  
  for i in range(n):
    row = []
    for j in range(m):
      curr_cell = 0
      for t in range(m1.m):
        curr_cell += m1.matrix[i][t] * m2.matrix[t][j]
      row.append(curr_cell)
    out_matrix.append(row)
  return out_matrix

In [ ]:
prod_matrix(m1,m1)

[[7, 6, 8], [9, 10, 12], [0, 0, 1]]

In [ ]:
# Найти произведение матрицы k = [[2,-3],[4,-6]] и l = [[9,-6],[6,-4]]


k = Matrix([[2,-3],[4,-6]])
l = Matrix([[9,-6],[6,-4]])

In [ ]:
prod_matrix(k,l)

[[0, 0], [0, 0]]

In [ ]:
#KL != LK
prod_matrix(l,k)

[[-6, 9], [-4, 6]]

In [ ]:
# Обратная матрица:
np.linalg.inv(m1.matrix).tolist()

[[-0.4999999999999999, 0.5, 0.9999999999999997],
 [0.7499999999999999, -0.24999999999999994, -1.9999999999999996],
 [0.0, 0.0, 1.0]]

In [ ]:
inv_m1 = Matrix(np.linalg.inv(m1.matrix).tolist())
E = np.array(prod_matrix(inv_m1,m1),dtype='float16')
print (E)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##Скаляры, векторы и матрицы с помощью библиотеки Numpy

In [ ]:
import numpy as np

In [ ]:
scalar1 = 1
scalar2 = 5
scalar3 = 17.345
scalar4 = -3.2476

print('Скаляры')
print(scalar1)
print(scalar2)
print(scalar3)
print(scalar4)

Скаляры
1
5
17.345
-3.2476


In [ ]:
vector = np.array([1.3, 4.2, -2.2, 13.1])
vector_vertical = np.array([1.3, 4.2, -2.2, 13.1]).reshape((4,1))

print('Горизонтальный вектор:', vector)

print('Вертикальный вектор:\n', vector_vertical)

Горизонтальный вектор: [ 1.3  4.2 -2.2 13.1]
Вертикальный вектор:
 [[ 1.3]
 [ 4.2]
 [-2.2]
 [13.1]]


In [ ]:
print(vector.shape)
print(vector_vertical.shape)

(4,)
(4, 1)


In [ ]:
def print_vector(v):
  shape = v.shape
  
  if (len(shape) == 0):
    print(v)
    
  if (len(shape) == 1):
    s = ''
    for i in v:
      s += str(i) + '  '
    print(s)
      
  if (len(shape) == 2):
    for i in range(shape[0]):
      s = ''
      for j in range(shape[1]):
        s += str(v[i][j]) + '  '
      print(s)

In [ ]:
print_vector(vector)

1.3  4.2  -2.2  13.1  


In [ ]:
print_vector(vector_vertical)

1.3  
4.2  
-2.2  
13.1  


##Операции с векторами

**Добавление и вычитание скаляра**

In [ ]:
print_vector(vector)
print_vector(vector + 1)
print_vector(vector - 2)

1.3  4.2  -2.2  13.1  
2.3  5.2  -1.2000000000000002  14.1  
-0.7  2.2  -4.2  11.1  


**Умножение на скаляр**

In [ ]:
print_vector(vector * 2)

2.6  8.4  -4.4  26.2  


**Деление на скаляр**

In [ ]:
print_vector(vector / 4)

0.325  1.05  -0.55  3.275  


**Возведение в степень**

In [ ]:
print_vector(vector ** 2)

1.6900000000000002  17.64  4.840000000000001  171.60999999999999  


**Сложение и вычитание векторов**

In [ ]:
vector1 = np.array([0, 1, 2, 3])
vector2 = np.array([1, 2, 3, 4])

In [ ]:
print_vector(vector1 + vector2)

1  3  5  7  


In [ ]:
print_vector(vector1 - vector2)

-1  -1  -1  -1  


**Умножение и деление векторов**

In [ ]:
print_vector(vector1 * vector2)

0  2  6  12  


In [ ]:
print_vector(vector1 / vector2)

0.0  0.5  0.6666666666666666  0.75  


**Возведение в степень**

In [ ]:
print_vector(vector1 ** vector2)

0  1  8  81  


##Пример матрицы

In [ ]:
matrix = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4]])

In [ ]:
print_vector(matrix)

0  1  2  
1  2  3  
2  3  4  


##Цикл по матрице
Для примера найдём максимум матрицы

In [ ]:
matrix2 = np.array([[145, 23, 191], [17, 252, 31], [99, 112, 39]])
print_vector(matrix2)

145  23  191  
17  252  31  
99  112  39  


In [ ]:
matrix_max = 0

for i in range(matrix2.shape[0]):
  for j in range(matrix2.shape[1]):
    if (matrix2[i,j] > matrix_max):
      matrix_max = matrix2[i,j]

print('Максимум матрицы =', matrix_max)

Максимум матрицы = 252


In [ ]:
np.max(matrix2)

252

##Операции с матрицами

In [ ]:
print_vector(matrix)

0  1  2  
1  2  3  
2  3  4  


In [ ]:
print('Сложение')
print_vector(matrix + 1)

print()
print('Умножение')
print_vector(matrix * 2)

print()
print('Деление')
print_vector(matrix / 4)

print()
print('Возведение в степень')
print_vector(matrix ** 2)

Сложение
1  2  3  
2  3  4  
3  4  5  

Умножение
0  2  4  
2  4  6  
4  6  8  

Деление
0.0  0.25  0.5  
0.25  0.5  0.75  
0.5  0.75  1.0  

Возведение в степень
0  1  4  
1  4  9  
4  9  16  


In [ ]:
print_vector(matrix2)

145  23  191  
17  252  31  
99  112  39  


In [ ]:
print('Сложение')
print_vector(matrix + matrix2)

print()
print('Умножение')
print_vector(matrix * matrix2)

print()
print('Деление')
print_vector(matrix / matrix2)

print()
print('Возведение в степень')
print_vector(matrix2 ** matrix)

Сложение
145  24  193  
18  254  34  
101  115  43  

Умножение
0  23  382  
17  504  93  
198  336  156  

Деление
0.0  0.043478260869565216  0.010471204188481676  
0.058823529411764705  0.007936507936507936  0.0967741935483871  
0.020202020202020204  0.026785714285714284  0.10256410256410256  

Возведение в степень
1  23  36481  
17  63504  29791  
9801  1404928  2313441  


In [ ]:
def prod_matrix(matrix1, matrix2):
  shape1 = matrix1.shape
  shape2 = matrix2.shape
  
  if (shape1[1] != shape2[0]):
    return np.array([])
  
  out_matrix = np.zeros((shape1[0], shape2[1]))
  
  for i in range(shape1[0]):
    for j in range(shape2[1]):
      curr_cell = 0
      for t in range(shape1[1]):
        curr_cell += matrix1[i,t] * matrix2[t,j]
        out_matrix[i,j] = curr_cell
  
  return out_matrix

In [ ]:
matrix1 = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5]])
matrix2 = np.array([[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]])

print_vector(matrix1)
print()
print_vector(matrix2)

0  1  2  
1  2  3  
2  3  4  
3  4  5  

0  1  2  3  
1  2  3  4  
2  3  4  5  


In [ ]:
matrix3 = prod_matrix(matrix1, matrix2)
print_vector(matrix3)

5.0  8.0  11.0  14.0  
8.0  14.0  20.0  26.0  
11.0  20.0  29.0  38.0  
14.0  26.0  38.0  50.0  


In [ ]:
vector1 = np.array([1, 2, 3, 4]).reshape((1,4))
vector2 = np.array([5, 4, 3]).reshape((3,1))

print('Первый вектор')
print_vector(vector1)
print()
print('Второй вектор')
print_vector(vector2)


matrix4 = prod_matrix(vector2, vector1)

print()
print('Итоговая матрица')
print_vector(matrix4)

print()
print('Проверка размерности')
print(vector2.shape)
print(vector1.shape)
print(matrix4.shape)

Первый вектор
1  2  3  4  

Второй вектор
5  
4  
3  

Итоговая матрица
5.0  10.0  15.0  20.0  
4.0  8.0  12.0  16.0  
3.0  6.0  9.0  12.0  

Проверка размерности
(3, 1)
(1, 4)
(3, 4)


In [ ]:
def transpose_matrix(matrix):
  shape = matrix.shape
  
  out_matrix = np.zeros((shape[1], shape[0]))
  
  for i in range(shape[0]):
    for j in range(shape[1]):
      out_matrix[j,i] = matrix[i,j]
  
  return out_matrix

In [ ]:
transpose_matrix = transpose_matrix(matrix1)

print('Оригинальная матрица')
print_vector(matrix1)

print()
print('Транспонированная матрица')
print_vector(transpose_matrix)

Оригинальная матрица
0  1  2  
1  2  3  
2  3  4  
3  4  5  

Транспонированная матрица
0.0  1.0  2.0  3.0  
1.0  2.0  3.0  4.0  
2.0  3.0  4.0  5.0  


In [ ]:
matrix_4_inv = np.array([[4, 1, 3], [3, 5, 2], [2, 6, 4]])

In [ ]:
inv_matrix = np.linalg.inv(matrix_4_inv)
print_vector(inv_matrix)

0.16666666666666669  0.29166666666666663  -0.2708333333333333  
-0.16666666666666669  0.20833333333333337  0.020833333333333322  
0.16666666666666669  -0.45833333333333337  0.3541666666666667  


In [ ]:
result_matrix = prod_matrix(matrix_4_inv, inv_matrix)
print_vector(result_matrix)

1.0  0.0  0.0  
-1.1102230246251565e-16  1.0000000000000002  0.0  
1.1102230246251565e-16  0.0  1.0  


#Домашнее задание

Задачи Лайт:

**Задача 1**
а) Даны точки A(-2,5) и B(1,7) . Найти векторы  AB и BA.
б) Даны точки A(-1,-1) , B(1,1)  и C(0,2). Найти векторы AB, AC и BC.
в) Даны точки  A(-1,3,1) и B(3,2,7) . Найти векторы AB и BA.

**Задача 2**
Дано:
A(-2,5) и B(1,7) Найти модуль вектора AB

**Задача 3**
Даны векторы a(1,4,-5) и b(2,-5,3) найти 3a-2b, -a + 4b

**Задача 4**
Даны векторы a(0,2,-1) и b(1,-4,2)и c(0,3,0) найти 3a-5b+0,5c

**Задача 6**
Найти скалярное произведение векторов a(2,4) и b(0,-1) , если угол между a и b = pi/2

**Задача 7**
Найти угол между векторами a и b, если известно, что |a| = 4 и |b| = 2* np.sqrt(2), a*b = 8

**Задача 8**
Какой знак будет у скалярного произведения a и b, если известно, что угол(a,b) равен:
а) pi/3 б)pi

**Задача 9**
Даны матрицы k = [[2,-3],[4,-6]] и l = [[9,-6],[6,-4]] вычислить:
a) 3k, b) 1/2*l c) k-l d) l+k


In [ ]:
import numpy as np

def print_vector(v):
  shape = v.shape
  
  if (len(shape) == 0):
    print(v)
    
  if (len(shape) == 1):
    s = ''
    for i in v:
      s += str(i) + '  '
    print(s)
      
  if (len(shape) == 2):
    for i in range(shape[0]):
      s = ''
      for j in range(shape[1]):
        s += str(v[i][j]) + '  '
      print(s)

# модуль вектора
def module(vector):
  return (np.sqrt( sum(item ** 2 for item in vector) ))

In [ ]:
# Задача 1 
# а) Даны точки A(-2,5) и B(1,7) . Найти векторы AB и BA. 
A = np.array([-2,5])
B = np.array([1,7])
print('A =',A,';','B =',B,';','координаты вектора AB(b1-a1,b2-a2):',B - A,';','координаты вектора BA(a1-b1,a2-b2):',A - B)

# б) Даны точки A(-1,-1) , B(1,1) и C(0,2). Найти векторы AB, AC и BC. 
A = np.array([-1,-1])
B = np.array([1,1])
C = np.array([0,2])
print('A =',A,';','B =',B,';','C =',C,';','координаты вектора AB(b1-a1,b2-a2):',B - A,';','координаты вектора AC(c1-a1,c2-a2):',C - A,';','координаты вектора BC(a1-b1,a2-b2):',C - B)

# в) Даны точки A(-1,3,1) и B(3,2,7) . Найти векторы AB и BA.
A = np.array([-1,3,1])
B = np.array([3,2,7])
print('A =',A,';','B =',B,';','координаты вектора AB(b1-a1,b2-a2):',B - A,';','координаты вектора BA(a1-b1,a2-b2):',A - B)


A = [-2  5] ; B = [1 7] ; координаты вектора AB(b1-a1,b2-a2): [3 2] ; координаты вектора BA(a1-b1,a2-b2): [-3 -2]
A = [-1 -1] ; B = [1 1] ; C = [0 2] ; координаты вектора AB(b1-a1,b2-a2): [2 2] ; координаты вектора AC(c1-a1,c2-a2): [1 3] ; координаты вектора BC(a1-b1,a2-b2): [-1  1]
A = [-1  3  1] ; B = [3 2 7] ; координаты вектора AB(b1-a1,b2-a2): [ 4 -1  6] ; координаты вектора BA(a1-b1,a2-b2): [-4  1 -6]


In [ ]:
# Задача 2 
# Дано: A(-2,5) и B(1,7) Найти модуль вектора AB
A = np.array([-2,5])
B = np.array([1,7])
AB = B - A
print ('A = {}; B = {}; AB = {}; Module |AB|: {}'.format(A, B, AB, np.sqrt( sum(item ** 2 for item in AB) )))

A = [-2  5]; B = [1 7]; AB = [3 2]; Module |AB|: 3.605551275463989


In [ ]:
# Задача 3 
# Даны векторы a(1,4,-5) и b(2,-5,3) найти 3a-2b, -a + 4b
A = np.array([1,4,-5])
B = np.array([2,-5,3])
print ('A = {}; B = {}; 3*A - 2*B = {}; -A + 4*B = {}'.format(A, B, 3*A - 2*B, -A + 4*B))

A = [ 1  4 -5]; B = [ 2 -5  3]; 3*A - 2*B = [ -1  22 -21]; -A + 4*B = [  7 -24  17]


In [ ]:
# Задача 4 
# Даны векторы a(0,2,-1) и b(1,-4,2)и c(0,3,0) найти 3a-5b+0,5c
A = np.array([0,2,-1])
B = np.array([1,-4,2])
C = np.array([0,3,0])
print ('A = {}; B = {}; C = {}; 3*A - 5*B + 0.5*C = {}'.format(A, B, C, 3*A - 5*B + 0.5*C))

A = [ 0  2 -1]; B = [ 1 -4  2]; C = [0 3 0]; 3*A - 5*B + 0.5*C = [ -5.   27.5 -13. ]


In [ ]:
# Задача 6 
# Найти скалярное произведение векторов a(2,4) и b(0,-1) , если угол между a и b = pi/2
a = np.array([2,4])
b = np.array([0,-1])
print ('a = {}; b = {}'.format(a,b))
result = np.dot(a, b)
ma = module(a)
mb =  module(b)
print ('result, ma,  mb = {} {} {}'.format(result, ma,  mb))
cos = result/(ma * mb)
print ('cos между векторами a и b = {}'.format(cos))
alpha = np.arccos( cos )
print ('угол между векторами a и b = {}'.format(alpha))
print ('pi/2 = {}'.format(np.pi/2))

if alpha == np.pi/2:
  print(np.dot(a, b))
  print('or')
  #  Эквивалентно:
  print(np.inner(a, b))    #  предпочтительнее
  print('or')
  #  Эквивалентно:
  print(np.sum(a*b))
else:
  print('угол между a и b != pi/2')


a = [2 4]; b = [ 0 -1]
result, ma,  mb = -4 4.47213595499958 1.0
cos между векторами a и b = -0.8944271909999159
угол между векторами a и b = 2.677945044588987
pi/2 = 1.5707963267948966
угол между a и b != pi/2


In [ ]:
# Задача 7
# Найти угол между векторами a и b, если известно, что |a| = 4 и |b| = 2* np.sqrt(2), a*b = 8
dot_product = 8
ma = 4
mb =  2 * np.sqrt(2)
print ('dot_product, ma,  mb = {} {} {}'.format(dot_product, ma,  mb))
cos = dot_product/(ma * mb)
print ('cos между векторами a и b = {}'.format(cos))
alpha = np.arccos( cos )
print ('угол между векторами a и b = {}'.format(alpha))

print ('угол между векторами равен pi/4:',round(alpha, 8) == round(np.pi/4, 8))


dot_product, ma,  mb = 8 4 2.8284271247461903
cos между векторами a и b = 0.7071067811865475
угол между векторами a и b = 0.7853981633974484
угол между векторами равен pi/4: True


In [ ]:
# Задача 8 
# Какой знак будет у скалярного произведения a и b, если известно, что угол(a,b) равен: а) pi/3 б)pi
print("""
  Cкалярное произведение больше нуля для угла между векторами меньше pi/2 и меньше нуля для угла между векторами меньше pi/2.
  a) при угле pi/3 скалярное произведение будет больше нуля
  б) при угле pi скалярное произведение будет меньше нуля
""")


  Cкалярное произведение больше нуля для угла между векторами меньше pi/2 и меньше нуля для угла между векторами меньше pi/2.
  a) при угле pi/3 скалярное произведение будет больше нуля
  б) при угле pi скалярное произведение будет меньше нуля



In [ ]:
# Задача 9 
# Даны матрицы k = [[2,-3],[4,-6]] и l = [[9,-6],[6,-4]] вычислить: a) 3k, b) 1/2*l c) k-l d) l+k
k = np.array([[2,-3],[4,-6]])
l = np.array([[9,-6],[6,-4]])
print('k = \n{}; \n\nl = \n{}; \n\n3*k = \n{}; \n\n1./2*l = \n{}; \n\nk-l = \n{}; \n\nl+k = \n{}'.format(k, l, 3*k, 1./2*l, k-l, l+k))

k = 
[[ 2 -3]
 [ 4 -6]]; 

l = 
[[ 9 -6]
 [ 6 -4]]; 

3*k = 
[[  6  -9]
 [ 12 -18]]; 

1./2*l = 
[[ 4.5 -3. ]
 [ 3.  -2. ]]; 

k-l = 
[[-7  3]
 [-2 -2]]; 

l+k = 
[[ 11  -9]
 [ 10 -10]]


In [ ]:
# Задача 9 
# Даны матрицы k = [[2,-3],[4,-6]] и l = [[9,-6],[6,-4]] вычислить: a) 3k, b) 1/2*l c) k-l d) l+k
k = np.array([[2,-3],[4,-6]])
l = np.array([[9,-6],[6,-4]])
print('k =')
print_vector(k)
print('\nl =')
print_vector(l)
print('\n3*k =')
print_vector(3*k)
print('\n1./2*l =')
print_vector(1./2*l)
print('\nk-l =')
print_vector(k-l)
print('\nl+k =')
print_vector(l+k)


k =
2  -3  
4  -6  

l =
9  -6  
6  -4  

3*k =
6  -9  
12  -18  

1./2*l =
4.5  -3.0  
3.0  -2.0  

k-l =
-7  3  
-2  -2  

l+k =
11  -9  
10  -10  


ПРО

**Задача 1**
Найти скалярное произведение векторов с=-2a+b и d=a-b , если известно, что: a и b - вектора, |a| = 4* np.sqrt(2) и |b| = 8, угол(a,b) = pi/4 

**Задача 2**
Найти модуль векторов с=—a+3b , если известно, что: a и b - вектора, |a| = 3 и |b| = 2, угол(a,b) = pi/3 

**Задача 3**
Найти угол между векторами c=-2a+3b и d=4a-3b, если известно, что |a| = 3 и |b| = 4, угол(a,b) = pi/3 

**Задача 4**
Даны матрицы k = [[5,8,-4],[6,9,-5],[4,7,-3]] и l = [[3,2,5],[4,-1,3],[9,6,5]] произведите умножение kl и lk

In [ ]:
# Задача 1 
# Найти скалярное произведение векторов с=-2a+b и d=a-b , если известно, что: a и b - вектора, |a| = 4* np.sqrt(2) и |b| = 8, угол(a,b) = pi/4
ma = 4* np.sqrt(2) # = np.sqrt( ax ** 2 + ay **2 )
mb = 8  # = np.sqrt( bx ** 2 + by **2 )
alpha = pi/4
ab = ma * mb * cox(alpha)

# cd  =  ???

# ax*ay+bx*by = ab
# ax ** 2 + ay ** 2 = ma ** 2
# bx ** 2 + by ** 2 = mb ** 2
# Пусть by = 0
# тогда
# bx = mb
# ax*ay = ab
# ax ** 2 + ay ** 2 = ma ** 2
# ...

In [ ]:
# нахождение угла:
# угол = arccos(a*b/|a|*|b|)
a = vector_2d(coords=(1,4))
b = vector_2d(coords=(-3,2))
a_b = 12.874393189583733
ang = a_b/(a.get_module() * b.get_module()) 
print (" Угол равен = {}".format(np.arccos(ang)))  



 Угол равен = 0.5235987755982987


In [ ]:
# Скалярное произведение векторов в координатах
# a(x1,x2)* b(y1,y2) = ab(x1*y1+x2*y2)
print (" Скалярное произведение ab в координатах = {}".format(a.x*b.x + a.y*b.y))  

 Скалярное произведение ab в координатах = 5


In [ ]:
# Задача 4 
# Даны матрицы k = [[5,8,-4],[6,9,-5],[4,7,-3]] и l = [[3,2,5],[4,-1,3],[9,6,5]] произведите умножение kl и lk

def matrix_multiply(m1,m2):
    try:
      s1i = len(m1)
      s1j = len(m1[0])
    except Exception as ex:
      print('Ошибка в размерности исходных данных m1: ', ex)
      return
    try:
      s2i = len(m2)
      s2j = len(m2[0])
    except Exception as ex:
      print('Ошибка в размерности исходных данных m2: ', ex)
      return

    if s1j!=s2i:
      return 'Несовместимые размерности матриц m1 и m2'
    else:  
      mid_matrix = []
      for i in range(s1i):
        row = []
        for j in range(s2j):
          curr_cell = 0
          for t in range(s1j):
            curr_cell += m1[i][t] * m2[t][j]
          row.append(curr_cell)
        mid_matrix.append(row)
    return mid_matrix

k = [[5,8,-4],[6,9,-5],[4,7,-3]] 
l = [[3,2,5],[4,-1,3],[9,6,5]]

In [ ]:
matrix_multiply(k, l)

[[11, -22, 29], [9, -27, 32], [13, -17, 26]]

In [ ]:
matrix_multiply(l, k)

[[47, 77, -37], [26, 44, -20], [101, 161, -81]]

## Задачи на работу с кодом

**Задача 1**

Напишите функцию умножения трёх матриц

In [ ]:
def triple_multiply(m1,m2,m3):
    try:
      s1i = len(m1)
      s1j = len(m1[0])
    except Exception as ex:
      print('Ошибка в размерности исходных данных m1: ', ex)
      return
    try:
      s2i = len(m2)
      s2j = len(m2[0])
    except Exception as ex:
      print('Ошибка в размерности исходных данных m2: ', ex)
      return
    try:
      s3i = len(m3)
      s3j = len(m3[0])
    except Exception as ex:
      print('Ошибка в размерности исходных данных m3: ', ex)
      return

    if s1j!=s2i:
      return 'Несовместимые размерности матриц m1 и m2'
    # mid_matrix.shape == [s1i,s2j]
    elif s1i!=s3i:
      return 'Несовместимые размерности матриц m1 и m3' 
    else:  
      mid_matrix = []
      for i in range(s1i):
        row = []
        for j in range(s2j):
          curr_cell = 0
          for t in range(s1j):
            curr_cell += m1[i][t] * m2[t][j]
          row.append(curr_cell)
        mid_matrix.append(row)
    # return mid_matrix

      out_matrix = []
      # mid_matrix.shape == [s1i,s2j]
      for i in range(s1i):
        row = []
        for j in range(s3j):
          curr_cell = 0
          for t in range(s2j):
            curr_cell += mid_matrix[i][t] * m3[t][j]
          row.append(curr_cell)
        out_matrix.append(row)
    return out_matrix


**Check-list triple_multiply**

In [ ]:
np.array([[1,1],[1,1],[1,1]])

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
np.array([[1,1],[1,1],[1,1]]).shape

(3, 2)

In [ ]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.array([[2,2,2],[2,2,2]]).shape

(2, 3)

In [ ]:
m12 = np.dot(np.array([[1,1],[1,1],[1,1]]), np.array([[2,2,2],[2,2,2]]))
m12

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
m123 = np.dot(m12, np.array([[3],[3],[3]]))
m123

array([[36],
       [36],
       [36]])

In [ ]:
m123.shape

(3, 1)

In [ ]:
triple_multiply([[1,1],[1,1],[1,1]],
                [[2,2,2],[2,2,2]],
                [[3],[3],[3]])

[[36], [36], [36]]

**Задача 2**

Напишите функцию, которая считает разницу между максимальным и минимальным элементами матрицы

In [ ]:
def delta_min_max_1(m):
  check_matrix = np.array(m)
  shape = check_matrix.shape
  max_len = 1
  for sh in range(len(shape)):
    max_len *= shape[sh]
  a = np.reshape(m, (max_len))
  vmin = min(a)
  vmax = max(a)
  return vmax - vmin

In [ ]:
delta_min_max_1([[[1,0],[1,1],[1,1]],
                 [[2,2],[2,2],[1,9]],
                 [[3,2],[2,2],[1,-3]]])

12

In [ ]:
def delta_min_max_2(m):
  check_matrix = np.array(m)
  return check_matrix.max() - check_matrix.min()

In [ ]:
delta_min_max_2([[[1,0],[1,1],[1,1]],
                 [[2,2],[2,2],[1,9]],
                 [[3,2],[2,2],[1,-3]]])

12

**Задача 3**

Напишите функцию, которая
- умножает матрицу на саму себя, но транспонированную
- берёт обратную матрицу от результата

In [ ]:
def matrix_multiply(m1,m2):
    try:
      s1i = len(m1)
      s1j = len(m1[0])
    except Exception as ex:
      print('Ошибка в размерности исходных данных m1: ', ex)
      return
    try:
      s2i = len(m2)
      s2j = len(m2[0])
    except Exception as ex:
      print('Ошибка в размерности исходных данных m2: ', ex)
      return

    if s1j!=s2i:
      return 'Несовместимые размерности матриц m1 и m2'
    else:  
      mid_matrix = []
      for i in range(s1i):
        row = []
        for j in range(s2j):
          curr_cell = 0
          for t in range(s1j):
            curr_cell += m1[i][t] * m2[t][j]
          row.append(curr_cell)
        mid_matrix.append(row)
    return mid_matrix


def transpose_matrix(m):
  shape = np.array(m).shape
  
  out_matrix = np.zeros((shape[1], shape[0]))
  
  for i in range(shape[0]):
    for j in range(shape[1]):
      out_matrix[j][i] = m[i][j]
  
  return out_matrix

def translate_matrix_1(m):
  r = matrix_multiply(m,transpose_matrix(m))
  print('matrix_multiply =',r)
  try:
    return np.linalg.inv(r)
  except:  
    return 'Обратная матрица отсутствует'

def translate_matrix_2(m):
  r = matrix_multiply(m,transpose_matrix(m))
  # fix LinAlgError: Singular matrix
  s1 = len(r)
  s2 = len(r[0])
  print('matrix_multiply =',r)
  noiseR = np.array(r) + 0.0000001*np.random.rand(s1, s2)
  return np.linalg.inv(noiseR)

In [ ]:
translate_matrix_1([[3,1],[6,-3],[6,10]])

matrix_multiply = [[10.0, 15.0, 28.0], [15.0, 45.0, 6.0], [28.0, 6.0, 136.0]]


array([[-4.87889960e+14,  1.50119988e+14,  9.38249922e+13],
       [ 1.50119988e+14, -4.61907654e+13, -2.88692284e+13],
       [ 9.38249922e+13, -2.88692284e+13, -1.80432677e+13]])

In [ ]:
translate_matrix_2([[3,1],[6,-3],[6,10]])

matrix_multiply = [[10.0, 15.0, 28.0], [15.0, 45.0, 6.0], [28.0, 6.0, 136.0]]


array([[-52249357.66062883,  16076725.48351859,  10047953.41297748],
       [ 16076725.51971304,  -4946684.7681669 ,  -3091677.99068569],
       [ 10047953.40728747,  -3091677.98197444,  -1932298.72798628]])

In [ ]:
translate_matrix_1([[1,2],[1,1],[1,1]])

matrix_multiply = [[5.0, 3.0, 3.0], [3.0, 2.0, 2.0], [3.0, 2.0, 2.0]]


'Обратная матрица отсутствует'

In [ ]:
translate_matrix_2([[1,2],[1,1],[1,1]])

matrix_multiply = [[5.0, 3.0, 3.0], [3.0, 2.0, 2.0], [3.0, 2.0, 2.0]]


array([[ 2.00000041e+00,  1.06363999e-01, -3.10636461e+00],
       [-5.79214294e+00, -2.14714900e+07,  2.14714994e+07],
       [ 2.79214231e+00,  2.14714901e+07, -2.14714945e+07]])